services:

  wordpress:
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: example-123
      WORDPRESS_DB_NAME: wp_standard 
      WORDPRESS_DEBUG: true 
      WORDPRESS_DEBUG_LOG: true 
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    build:
      dockerfile: ./WordPress.Dockerfile

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  
    environment:
      MYSQL_DATABASE: wp_standard
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: example-123
      MYSQL_ROOT_PASSWORD: rootpass 
    volumes:
      - db:/var/lib/mysql

  wpcli:
    build:
      dockerfile: ./WPcli.Dockerfile
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins

    network_mode: service:wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: example-123
      WORDPRESS_DB_NAME: wp_standard
    entrypoint: ["wp"]
    command: ["user", "list"]

volumes:
  wordpress:
  db:
  plugins:
