services:

  wordpress:
    image: wordpress:6.9-php8.3
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: example-123
      WORDPRESS_DB_NAME: wp_standard 
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  
    environment:
      MYSQL_DATABASE: wp_standard
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: example-123
      MYSQL_ROOT_PASSWORD: rootpass 
    volumes:
      - db:/var/lib/mysql

  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    network_mode: service:wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: example-123
      WORDPRESS_DB_NAME: wp_standard
    entrypoint: ["wp"]
    command: ["user", "list"]

volumes:
  wordpress:
  db:
